[project]
name = "stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.26.0",
    "pyarrow>=19.0.1",
    "requests>=2.32.3",
    "ydata-profiling>=4.16.1",
]
